Q1.If you have any, what are your choices for increasing the comparison between different figures on the same graph?

ANS:- Bar plot, line plot, scatter plot

Q2.Can you explain the benefit of compound interest over a higher rate of interest that does not compound after reading this chapter?

ANS:- Compound interest makes your money grow faster because interest is calculated on the accumulated interest over time as well as on your original principal.

Q3.What is a histogram, exactly? Name a numpy method for creating such a graph.

ANS:- A histogram is an approximate representation of the distribution of numerical data. numpy.histogram()

Q4.If necessary, how do you change the aspect ratios between the X and Y axes?

ANS:- figure(figsize=(10,20))

Q5.Compare and contrast the three types of array multiplication between two numpy arrays: dot product, outer product, and regular multiplication of two numpy arrays.

In [1]:
import numpy as np

In [5]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[4,5],[6,7]])

In [11]:
np.dot(a1,a2)

array([[16, 19],
       [36, 43]])

In [13]:
np.outer(a1,a2)

array([[ 4,  5,  6,  7],
       [ 8, 10, 12, 14],
       [12, 15, 18, 21],
       [16, 20, 24, 28]])

In [14]:
np.multiply(a1,a2)

array([[ 4, 10],
       [18, 28]])

Q6.Before you buy a home, which numpy function will you use to measure your monthly mortgage payment?

ANS:- np.pmt(rate, nper, pv)

rate = The periodic interest rate

nper = The number of payment periods

pv = The total value of the mortgage loan

Q7.Can string data be stored in numpy arrays? If so, list at least one restriction that applies to this data.

ANS:- Yes it can be stored.

In [19]:
a=np.array(['abc','def'])
a

array(['abc', 'def'], dtype='<U3')

In [21]:
a[0]='ineuron'

In [22]:
a

array(['ine', 'def'], dtype='<U3')